// packages/vue/src/components/AllowlistChecker.vue
<script setup lang="ts">
import { ref, watch } from 'vue'
import { useWallet, useCandyMachine } from '../composables'

const props = defineProps<{
  candyMachine: string
  allowlist?: string[]
}>()

const emit = defineEmits<{
  result: [eligible: boolean]
}>()

const { publicKey } = useWallet()
const { loading } = useCandyMachine(() => props.candyMachine)
const eligible = ref<boolean | null>(null)

watch([publicKey, loading], () => {
  if (!publicKey.value || loading.value) {
    eligible.value = null
    return
  }

  const address = publicKey.value.toBase58()
  const isEligible = props.allowlist ? props.allowlist.includes(address) : true

  eligible.value = isEligible
  emit('result', isEligible)
}, { immediate: true })
</script>

<template>
  <div v-if="!publicKey">Connect your wallet to check eligibility</div>
  <div v-else-if="loading">Checking eligibility...</div>
  <div v-else-if="eligible === null">...</div>
  <div
    v-else
    :style="{
      padding: '8px 12px',
      borderRadius: '4px',
      background: eligible ? '#d4edda' : '#f8d7da',
      color: eligible ? '#155724' : '#721c24',
    }"
  >
    {{ eligible ? 'You are eligible to mint!' : 'Your wallet is not on the allowlist' }}
  </div>
</template>

// packages/react/src/components/AllowlistChecker.tsx
import React, { useState, useEffect } from 'react'
import type { CandyMachineProps } from '../types'
import { useWallet } from '../hooks'
import { useCandyMachine } from '../hooks'

export interface AllowlistCheckerProps extends CandyMachineProps {
  allowlist?: string[]
  onResult?: (eligible: boolean) => void
}

export function AllowlistChecker({ candyMachine, allowlist, onResult, className, style }: AllowlistCheckerProps): JSX.Element {
  const { publicKey } = useWallet()
  const { candyMachine: cm, loading } = useCandyMachine(candyMachine)
  const [eligible, setEligible] = useState<boolean | null>(null)

  useEffect(() => {
    if (!publicKey || loading) {
      setEligible(null)
      return
    }

    const address = publicKey.toBase58()
    const isEligible = allowlist ? allowlist.includes(address) : true

    setEligible(isEligible)
    onResult?.(isEligible)
  }, [publicKey, loading, allowlist, onResult])

  if (!publicKey) {
    return <div className={className} style={style}>Connect your wallet to check eligibility</div>
  }

  if (loading) {
    return <div className={className} style={style}>Checking eligibility...</div>
  }

  if (eligible === null) {
    return <div className={className} style={style}>...</div>
  }

  return (
    <div
      className={className}
      style={{
        padding: '8px 12px',
        borderRadius: 4,
        background: eligible ? '#d4edda' : '#f8d7da',
        color: eligible ? '#155724' : '#721c24',
        ...style,
      }}
    >
      {eligible ? 'You are eligible to mint!' : 'Your wallet is not on the allowlist'}
    </div>
  )
}
