// packages/vue/src/components/ExplorerLink.vue
<script setup lang="ts">
import { computed } from 'vue'

const props = withDefaults(defineProps<{
  signature?: string
  address?: string
  cluster?: 'mainnet-beta' | 'devnet' | 'testnet'
}>(), {
  cluster: 'devnet',
})

const url = computed(() => {
  const baseUrl = 'https://explorer.solana.com'
  const clusterParam = props.cluster === 'mainnet-beta' ? '' : `?cluster=${props.cluster}`

  if (props.signature) return `${baseUrl}/tx/${props.signature}${clusterParam}`
  if (props.address) return `${baseUrl}/address/${props.address}${clusterParam}`
  return '#'
})

const label = computed(() => {
  if (props.signature) return props.signature.slice(0, 8) + '...'
  if (props.address) return props.address.slice(0, 8) + '...'
  return 'View'
})
</script>

<template>
  <a :href="url" target="_blank" rel="noopener noreferrer" style="color: #1976D2; text-decoration: none;">
    {{ label }}
  </a>
</template>

// packages/react/src/components/ExplorerLink.tsx
import React from 'react'
import type { CommonProps } from '../types'

export interface ExplorerLinkProps extends CommonProps {
  signature?: string
  address?: string
  cluster?: 'mainnet-beta' | 'devnet' | 'testnet'
}

export function ExplorerLink({ signature, address, cluster = 'devnet', className, style }: ExplorerLinkProps): JSX.Element {
  const baseUrl = 'https://explorer.solana.com'
  const clusterParam = cluster === 'mainnet-beta' ? '' : `?cluster=${cluster}`

  const url = signature
    ? `${baseUrl}/tx/${signature}${clusterParam}`
    : address
    ? `${baseUrl}/address/${address}${clusterParam}`
    : '#'

  const label = signature ? signature.slice(0, 8) + '...' : address ? address.slice(0, 8) + '...' : 'View'

  return (
    <a href={url} target="_blank" rel="noopener noreferrer" className={className} style={{ color: '#1976D2', textDecoration: 'none', ...style }}>
      {label}
    </a>
  )
}
