// packages/vue/src/components/MintButton.vue
<script setup lang="ts">
import { ref } from 'vue'
import { useCandyMachine } from '../composables'

const props = withDefaults(defineProps<{
  candyMachine: string
  disabled?: boolean
}>(), {
  disabled: false,
})

const emit = defineEmits<{
  mint: []
}>()

const { candyMachine: cm, loading } = useCandyMachine(() => props.candyMachine)
const minting = ref(false)

const handleMint = async () => {
  if (props.disabled || minting.value || !cm.value || cm.value.isSoldOut) return
  minting.value = true
  try {
    emit('mint')
  } finally {
    minting.value = false
  }
}

const isDisabled = () => props.disabled || loading.value || minting.value || cm.value?.isSoldOut
const buttonText = () => {
  if (loading.value) return 'Loading...'
  if (minting.value) return 'Minting...'
  if (cm.value?.isSoldOut) return 'Sold Out'
  return 'Mint'
}
</script>

<template>
  <button
    @click="handleMint"
    :disabled="isDisabled()"
    :aria-label="loading ? 'Loading mint status' : minting ? 'Minting in progress' : cm?.isSoldOut ? 'Sold out' : 'Mint NFT'"
    :aria-busy="loading || minting"
    :aria-disabled="isDisabled()"
  >{{ buttonText() }}</button>
</template>

// packages/react/src/components/MintButton.tsx
import React from 'react'
import type { CandyMachineProps } from '../types'
import { useCandyMachine } from '../hooks'

export interface MintButtonProps extends CandyMachineProps {
  onMint?: () => void
  disabled?: boolean
}

export function MintButton({ candyMachine, onMint, disabled, className, style }: MintButtonProps): JSX.Element {
  const { candyMachine: cm, loading } = useCandyMachine(candyMachine)
  const [minting, setMinting] = React.useState(false)

  const handleMint = async () => {
    if (disabled || minting || !cm || cm.isSoldOut) return
    setMinting(true)
    try {
      onMint?.()
    } finally {
      setMinting(false)
    }
  }

  const isDisabled = disabled || loading || minting || cm?.isSoldOut

  return (
    <button
      className={className}
      style={style}
      onClick={handleMint}
      disabled={isDisabled}
      aria-label={loading ? 'Loading mint status' : minting ? 'Minting in progress' : cm?.isSoldOut ? 'Sold out' : 'Mint NFT'}
      aria-busy={loading || minting}
      aria-disabled={isDisabled}
    >
      {loading ? 'Loading...' : minting ? 'Minting...' : cm?.isSoldOut ? 'Sold Out' : 'Mint'}
    </button>
  )
}
