// packages/vue/src/components/NFTGrid.vue
<script setup lang="ts">
import { useNFTs } from '../composables'
import NFTCard from './NFTCard.vue'

const props = withDefaults(defineProps<{
  owner: string
  columns?: number
}>(), {
  columns: 3,
})

const { nfts, loading, error } = useNFTs(props.owner)
</script>

<template>
  <div v-if="loading" role="status" aria-label="Loading NFTs">Loading NFTs...</div>
  <div v-else-if="error" role="alert">Error: {{ error.message }}</div>
  <div v-else-if="nfts.length === 0">No NFTs found</div>
  <div v-else :style="{ display: 'grid', gridTemplateColumns: `repeat(${columns}, 1fr)`, gap: '16px' }" role="list" aria-label="NFT collection">
    <div v-for="nft in nfts" :key="nft.mint" role="listitem">
      <NFTCard :mint="nft.mint" />
    </div>
  </div>
</template>

// packages/react/src/components/NFTGrid.tsx
import React from 'react'
import type { CommonProps } from '../types'
import { useNFTs } from '../hooks'
import { NFTCard } from './NFTCard'

export interface NFTGridProps extends CommonProps {
  owner: string
  columns?: number
}

export function NFTGrid({ owner, columns = 3, className, style }: NFTGridProps): JSX.Element {
  const { nfts, loading, error } = useNFTs(owner)

  if (loading) return <div className={className} style={style} role="status" aria-label="Loading NFTs">Loading NFTs...</div>
  if (error) return <div className={className} style={style} role="alert">Error: {error.message}</div>
  if (nfts.length === 0) return <div className={className} style={style}>No NFTs found</div>

  return (
    <div className={className} style={{ display: 'grid', gridTemplateColumns: `repeat(${columns}, 1fr)`, gap: '16px', ...style }} role="list" aria-label="NFT collection">
      {nfts.map((nft) => (
        <div key={nft.mint} role="listitem">
          <NFTCard mint={nft.mint} nft={nft} />
        </div>
      ))}
    </div>
  )
}
