// packages/vue/src/components/NFTTransferButton.vue
<script setup lang="ts">
import { ref } from 'vue'
import { useTransaction } from '../composables'

defineProps<{
  mint: string
  disabled?: boolean
}>()

const emit = defineEmits<{
  transfer: [signature: string]
}>()

const { pending, error, send, reset } = useTransaction()
const showInput = ref(false)
const recipient = ref('')

const handleTransfer = async () => {
  if (!recipient.value.trim()) return
  reset()

  try {
    const sig = await send(new Uint8Array())
    emit('transfer', sig)
    showInput.value = false
    recipient.value = ''
  } catch {
    // Error captured in composable
  }
}
</script>

<template>
  <button v-if="!showInput" @click="showInput = true" :disabled="disabled || pending">
    Transfer NFT
  </button>
  <div v-else>
    <input
      v-model="recipient"
      type="text"
      placeholder="Recipient address"
      style="padding: 6px 8px; margin-right: 8px"
    />
    <button @click="handleTransfer" :disabled="pending || !recipient.trim()">
      {{ pending ? 'Sending...' : 'Send' }}
    </button>
    <button @click="showInput = false; recipient = ''" style="margin-left: 4px">
      Cancel
    </button>
    <div v-if="error" style="color: #e74c3c; font-size: 13px; margin-top: 4px">{{ error.message }}</div>
  </div>
</template>

// packages/react/src/components/NFTTransferButton.tsx
import React, { useState } from 'react'
import type { CommonProps } from '../types'
import { useTransaction } from '../hooks'

export interface NFTTransferButtonProps extends CommonProps {
  mint: string
  onTransfer?: (signature: string) => void
  disabled?: boolean
}

export function NFTTransferButton({ mint, onTransfer, disabled, className, style }: NFTTransferButtonProps): JSX.Element {
  const { pending, error, send, reset } = useTransaction()
  const [showInput, setShowInput] = useState(false)
  const [recipient, setRecipient] = useState('')

  const handleTransfer = async () => {
    if (!recipient.trim()) return
    reset()

    try {
      const sig = await send(new Uint8Array())
      onTransfer?.(sig)
      setShowInput(false)
      setRecipient('')
    } catch {
      // Error captured in hook
    }
  }

  if (!showInput) {
    return (
      <button
        className={className}
        style={style}
        onClick={() => setShowInput(true)}
        disabled={disabled || pending}
      >
        Transfer NFT
      </button>
    )
  }

  return (
    <div className={className} style={style}>
      <input
        type="text"
        value={recipient}
        onChange={(e) => setRecipient(e.target.value)}
        placeholder="Recipient address"
        style={{ padding: '6px 8px', marginRight: 8 }}
      />
      <button onClick={handleTransfer} disabled={pending || !recipient.trim()}>
        {pending ? 'Sending...' : 'Send'}
      </button>
      <button onClick={() => { setShowInput(false); setRecipient('') }} style={{ marginLeft: 4 }}>
        Cancel
      </button>
      {error && <div style={{ color: '#e74c3c', fontSize: 13, marginTop: 4 }}>{error.message}</div>}
    </div>
  )
}
