// packages/vue/src/components/TokenBalance.vue
<script setup lang="ts">
import { useTokenBalance } from '../composables'

const props = withDefaults(defineProps<{
  mint: string
  owner: string
  showSymbol?: boolean
  symbol?: string
}>(), {
  showSymbol: false,
  symbol: '',
})

const { uiBalance, loading, error } = useTokenBalance(props.mint, props.owner)
</script>

<template>
  <span v-if="loading" aria-busy="true" aria-label="Loading balance">...</span>
  <span v-else-if="error" role="alert">Error</span>
  <span v-else :aria-label="`Token balance: ${uiBalance.toLocaleString()}${showSymbol && symbol ? ` ${symbol}` : ''}`">{{ uiBalance.toLocaleString() }} <template v-if="showSymbol">{{ symbol }}</template></span>
</template>

// packages/react/src/components/TokenBalance.tsx
import React from 'react'
import type { TokenProps } from '../types'
import { useTokenBalance } from '../hooks'

export interface TokenBalanceProps extends TokenProps {
  owner: string
  showSymbol?: boolean
  symbol?: string
}

export function TokenBalance({ mint, owner, showSymbol, symbol, className, style }: TokenBalanceProps): JSX.Element {
  const { uiBalance, loading, error } = useTokenBalance(mint, owner)

  if (loading) return <span className={className} style={style} aria-busy={true} aria-label="Loading balance">...</span>
  if (error) return <span className={className} style={style} role="alert">Error</span>

  return (
    <span className={className} style={style} aria-label={`Token balance: ${uiBalance.toLocaleString()}${showSymbol && symbol ? ` ${symbol}` : ''}`}>
      {uiBalance.toLocaleString()} {showSymbol && symbol}
    </span>
  )
}
