// packages/vue/src/components/WalletBalance.vue
<script setup lang="ts">
import { ref, onMounted } from 'vue'
import { useConnection } from '../composables'

const props = withDefaults(defineProps<{
  address: string
  showSymbol?: boolean
}>(), {
  showSymbol: true,
})

const balance = ref<number>(0)
const connection = useConnection()

onMounted(async () => {
  const { PublicKey, LAMPORTS_PER_SOL } = await import('@solana/web3.js')
  const pubkey = new PublicKey(props.address)
  const lamports = await connection.getBalance(pubkey)
  balance.value = lamports / LAMPORTS_PER_SOL
})
</script>

<template>
  <span>{{ balance.toFixed(4) }} <template v-if="showSymbol">SOL</template></span>
</template>

// packages/react/src/components/WalletBalance.tsx
import React from 'react'
import type { CommonProps } from '../types'
import { useConnection } from '../context'

export interface WalletBalanceProps extends CommonProps {
  address: string
  showSymbol?: boolean
}

export function WalletBalance({ address, showSymbol = true, className, style }: WalletBalanceProps): JSX.Element {
  const [balance, setBalance] = React.useState<number>(0)
  const connection = useConnection()

  React.useEffect(() => {
    const fetchBalance = async () => {
      const { PublicKey, LAMPORTS_PER_SOL } = await import('@solana/web3.js')
      const pubkey = new PublicKey(address)
      const lamports = await connection.getBalance(pubkey)
      setBalance(lamports / LAMPORTS_PER_SOL)
    }
    fetchBalance()
  }, [connection, address])

  return (
    <span className={className} style={style}>
      {balance.toFixed(4)} {showSymbol && 'SOL'}
    </span>
  )
}
