// packages/vue/src/components/WalletAddress.vue
<script setup lang="ts">
import { computed } from 'vue'

const props = withDefaults(defineProps<{
  address: string
  truncate?: boolean
  chars?: number
}>(), {
  truncate: true,
  chars: 4,
})

const displayAddress = computed(() => {
  if (!props.truncate) return props.address
  return `${props.address.slice(0, props.chars)}...${props.address.slice(-props.chars)}`
})
</script>

<template>
  <span :title="address">{{ displayAddress }}</span>
</template>

// packages/react/src/components/WalletAddress.tsx
import type { CommonProps } from '../types'
import React from 'react'

export interface WalletAddressProps extends CommonProps {
  address: string
  truncate?: boolean
  chars?: number
}

export function WalletAddress({
  address,
  truncate = true,
  chars = 4,
  className,
  style,
}: WalletAddressProps): JSX.Element {
  const displayAddress = truncate
    ? `${address.slice(0, chars)}...${address.slice(-chars)}`
    : address

  return (
    <span className={className} style={style} title={address}>
      {displayAddress}
    </span>
  )
}
