// packages/vue/src/components/WalletDisconnectButton.vue
<script setup lang="ts">
import { useWallet } from '../composables'

const props = withDefaults(defineProps<{
  label?: string
}>(), {
  label: 'Disconnect',
})

const emit = defineEmits<{
  disconnect: []
}>()

const { connected, disconnect } = useWallet()

const handleClick = async () => {
  await disconnect()
  emit('disconnect')
}
</script>

<template>
  <button v-if="connected" @click="handleClick" aria-label="Disconnect wallet">
    {{ label }}
  </button>
</template>

// packages/react/src/components/WalletDisconnectButton.tsx
import React from 'react'
import type { WalletProps } from '../types'
import { useWallet } from '../hooks'

export interface WalletDisconnectButtonProps extends WalletProps {
  label?: string
}

export function WalletDisconnectButton({ label, onDisconnect, className, style }: WalletDisconnectButtonProps): JSX.Element | null {
  const { connected, disconnect } = useWallet()

  if (!connected) return null

  const handleClick = async () => {
    await disconnect()
    onDisconnect?.()
  }

  return (
    <button className={className} style={style} onClick={handleClick} aria-label="Disconnect wallet">
      {label ?? 'Disconnect'}
    </button>
  )
}
