// packages/vue/src/components/WalletConnectButton.vue
<script setup lang="ts">
import { useWallet } from '../composables'

const props = withDefaults(defineProps<{
  label?: string
  disabled?: boolean
}>(), {
  label: 'Connect Wallet',
  disabled: false,
})

const emit = defineEmits<{
  connect: []
}>()

const { connected, connecting, connect } = useWallet()

const handleClick = async () => {
  if (props.disabled || connecting.value || connected.value) return
  await connect()
  emit('connect')
}

const buttonText = () => {
  if (connecting.value) return 'Connecting...'
  if (connected.value) return 'Connected'
  return props.label
}
</script>

<template>
  <button
    @click="handleClick"
    :disabled="disabled || connecting || connected"
    :aria-label="connecting ? 'Connecting to wallet' : connected ? 'Wallet connected' : 'Connect wallet'"
    :aria-busy="connecting"
  >
    {{ buttonText() }}
  </button>
</template>

// packages/react/src/components/WalletConnectButton.tsx
import React from 'react'
import type { WalletProps } from '../types'
import { useWallet } from '../hooks'

export interface WalletConnectButtonProps extends WalletProps {
  label?: string
  disabled?: boolean
}

export function WalletConnectButton({ label, disabled, onConnect, className, style }: WalletConnectButtonProps): JSX.Element {
  const { connected, connecting, connect } = useWallet()

  const handleClick = async () => {
    if (disabled || connecting || connected) return
    await connect()
    onConnect?.()
  }

  const buttonText = connecting ? 'Connecting...' : connected ? 'Connected' : (label ?? 'Connect Wallet')

  return (
    <button
      className={className}
      style={style}
      onClick={handleClick}
      disabled={disabled || connecting || connected}
      aria-label={connecting ? 'Connecting to wallet' : connected ? 'Wallet connected' : 'Connect wallet'}
      aria-busy={connecting}
    >
      {buttonText}
    </button>
  )
}
