// packages/react/src/components/AddressDisplay.tsx
import React from 'react'
import type { CommonProps } from '../types'

export interface AddressDisplayProps extends CommonProps {
  address: string
  truncate?: boolean
  chars?: number
  copyable?: boolean
}

export function AddressDisplay({ address, truncate = true, chars = 4, copyable = true, className, style }: AddressDisplayProps): JSX.Element {
  const [copied, setCopied] = React.useState(false)

  const displayAddress = truncate ? `${address.slice(0, chars)}...${address.slice(-chars)}` : address

  const handleCopy = async () => {
    if (!copyable) return
    await navigator.clipboard.writeText(address)
    setCopied(true)
    setTimeout(() => setCopied(false), 2000)
  }

  return (
    <span className={className} style={{ cursor: copyable ? 'pointer' : 'default', fontFamily: 'monospace', ...style }} onClick={handleCopy} title={address}>
      {displayAddress} {copied && '✓'}
    </span>
  )
}

// packages/vue/src/components/AddressDisplay.vue
<script setup lang="ts">
import { ref, computed } from 'vue'

const props = withDefaults(defineProps<{
  address: string
  truncate?: boolean
  chars?: number
  copyable?: boolean
}>(), {
  truncate: true,
  chars: 4,
  copyable: true,
})

const copied = ref(false)

const displayAddress = computed(() => {
  if (!props.truncate) return props.address
  return `${props.address.slice(0, props.chars)}...${props.address.slice(-props.chars)}`
})

const handleCopy = async () => {
  if (!props.copyable) return
  await navigator.clipboard.writeText(props.address)
  copied.value = true
  setTimeout(() => { copied.value = false }, 2000)
}
</script>

<template>
  <span
    :style="{ cursor: copyable ? 'pointer' : 'default', fontFamily: 'monospace' }"
    @click="handleCopy"
    :title="address"
  >
    {{ displayAddress }} <template v-if="copied">✓</template>
  </span>
</template>
