// packages/react/src/components/MintPrice.tsx
import React from 'react'
import type { CandyMachineProps } from '../types'
import { useCandyMachine } from '../hooks'

export interface MintPriceProps extends CandyMachineProps {
  showSymbol?: boolean
  decimals?: number
}

export function MintPrice({ candyMachine, showSymbol = true, decimals = 4, className, style }: MintPriceProps): JSX.Element {
  const { candyMachine: cm, loading } = useCandyMachine(candyMachine)

  if (loading) return <span className={className} style={style}>...</span>
  if (!cm) return <span className={className} style={style}>--</span>

  const price = Number(cm.price) / 1e9

  return (
    <span className={className} style={style}>
      {price.toFixed(decimals)} {showSymbol && 'SOL'}
    </span>
  )
}

// packages/vue/src/components/MintPrice.vue
<script setup lang="ts">
import { computed } from 'vue'
import { useCandyMachine } from '../composables'

const props = withDefaults(defineProps<{
  candyMachine: string
  showSymbol?: boolean
  decimals?: number
}>(), {
  showSymbol: true,
  decimals: 4,
})

const { candyMachine: cm, loading } = useCandyMachine(props.candyMachine)

const price = computed(() => {
  if (!cm.value) return null
  return (Number(cm.value.price) / 1e9).toFixed(props.decimals)
})
</script>

<template>
  <span v-if="loading">...</span>
  <span v-else-if="!cm">--</span>
  <span v-else>{{ price }} <template v-if="showSymbol">SOL</template></span>
</template>
