// packages/react/src/components/MintCounter.tsx
import type { CandyMachineProps } from '../types'
import React from 'react'
import { useCandyMachine } from '../hooks'

export function MintCounter({ candyMachine, className, style }: CandyMachineProps): JSX.Element {
  const { candyMachine: cm, loading } = useCandyMachine(candyMachine)

  if (loading)
    return <span className={className} style={style}>...</span>
  if (!cm)
    return <span className={className} style={style}>-</span>

  return (
    <span className={className} style={style}>
      {cm.itemsMinted}
      {' '}
      /
      {cm.itemsAvailable}
    </span>
  )
}

// packages/vue/src/components/MintCounter.vue
<script setup lang="ts">
import { useCandyMachine } from '../composables'

const props = defineProps<{
  candyMachine: string
}>()

const { candyMachine: cm, loading } = useCandyMachine(() => props.candyMachine)
</script>

<template>
  <span v-if="loading">...</span>
  <span v-else-if="!cm">-</span>
  <span v-else>{{ cm.itemsMinted }} / {{ cm.itemsAvailable }}</span>
</template>
