// packages/react/src/components/MintProgress.tsx
import React from 'react'
import type { CandyMachineProps } from '../types'
import { useCandyMachine } from '../hooks'

export function MintProgress({ candyMachine, className, style }: CandyMachineProps): JSX.Element {
  const { candyMachine: cm, loading } = useCandyMachine(candyMachine)

  if (loading || !cm) return <div className={className} style={style} />

  const progress = (cm.itemsMinted / cm.itemsAvailable) * 100

  return (
    <div className={className} style={{ background: '#eee', borderRadius: '4px', overflow: 'hidden', ...style }}>
      <div style={{ width: `${progress}%`, height: '8px', background: '#4CAF50', transition: 'width 0.3s' }} />
    </div>
  )
}

// packages/vue/src/components/MintProgress.vue
<script setup lang="ts">
import { computed } from 'vue'
import { useCandyMachine } from '../composables'

const props = defineProps<{
  candyMachine: string
}>()

const { candyMachine: cm, loading } = useCandyMachine(() => props.candyMachine)

const progress = computed(() => {
  if (!cm.value) return 0
  return (cm.value.itemsMinted / cm.value.itemsAvailable) * 100
})
</script>

<template>
  <div v-if="!loading && cm" style="background: #eee; border-radius: 4px; overflow: hidden;">
    <div :style="{ width: `${progress}%`, height: '8px', background: '#4CAF50', transition: 'width 0.3s' }" />
  </div>
</template>
