// packages/react/src/components/NFTDetails.tsx
import React from 'react'
import type { NFTProps } from '../types'
import { useNFT } from '../hooks'

export function NFTDetails({ mint, className, style }: NFTProps): JSX.Element {
  const { nft, loading, error } = useNFT(mint)

  if (loading) return <div className={className} style={style}>Loading...</div>
  if (error) return <div className={className} style={style}>Error: {error.message}</div>
  if (!nft) return <div className={className} style={style}>NFT not found</div>

  return (
    <div className={className} style={style}>
      {nft.image && <img src={nft.image} alt={nft.name} style={{ maxWidth: '100%', borderRadius: '8px' }} />}
      <h2>{nft.name}</h2>
      <p><strong>Symbol:</strong> {nft.symbol}</p>
      <p><strong>Mint:</strong> {mint}</p>
      {nft.description && <p><strong>Description:</strong> {nft.description}</p>}
      {nft.attributes && nft.attributes.length > 0 && (
        <div>
          <strong>Attributes:</strong>
          <ul>
            {nft.attributes.map((attr, i) => (
              <li key={i}>{attr.trait_type}: {attr.value}</li>
            ))}
          </ul>
        </div>
      )}
    </div>
  )
}

// packages/vue/src/components/NFTDetails.vue
<script setup lang="ts">
import { useNFT } from '../composables'

const props = defineProps<{
  mint: string
}>()

const { nft, loading, error } = useNFT(props.mint)
</script>

<template>
  <div v-if="loading">
    Loading...
  </div>
  <div v-else-if="error">
    Error: {{ error.message }}
  </div>
  <div v-else-if="!nft">
    NFT not found
  </div>
  <div v-else>
    <img v-if="nft.image" :src="nft.image" :alt="nft.name" style="max-width: 100%; border-radius: 8px;">
    <h2>{{ nft.name }}</h2>
    <p><strong>Symbol:</strong> {{ nft.symbol }}</p>
    <p><strong>Mint:</strong> {{ mint }}</p>
    <p v-if="nft.description">
      <strong>Description:</strong> {{ nft.description }}
    </p>
    <div v-if="nft.attributes && nft.attributes.length > 0">
      <strong>Attributes:</strong>
      <ul>
        <li v-for="(attr, i) in nft.attributes" :key="i">
          {{ attr.trait_type }}: {{ attr.value }}
        </li>
      </ul>
    </div>
  </div>
</template>
