// packages/react/src/components/NFTGallery.tsx
import React from 'react'
import type { CommonProps } from '../types'
import { useNFTs } from '../hooks'
import { NFTCard } from './NFTCard'

export interface NFTGalleryProps extends CommonProps {
  owner: string
  collection?: string
  columns?: number
}

export function NFTGallery({ owner, collection, columns = 3, className, style }: NFTGalleryProps): JSX.Element {
  const { nfts, loading, error } = useNFTs(owner)

  if (loading) return <div className={className} style={style}>Loading gallery...</div>
  if (error) return <div className={className} style={style}>Error: {error.message}</div>

  const filtered = collection
    ? nfts.filter(nft => nft.collection === collection)
    : nfts

  if (filtered.length === 0) {
    return <div className={className} style={style}>No NFTs found{collection ? ' in this collection' : ''}</div>
  }

  return (
    <div
      className={className}
      style={{
        display: 'grid',
        gridTemplateColumns: `repeat(${columns}, 1fr)`,
        gap: 16,
        ...style,
      }}
    >
      {filtered.map(nft => (
        <NFTCard key={nft.mint} mint={nft.mint} />
      ))}
    </div>
  )
}

// packages/vue/src/components/NFTGallery.vue
<script setup lang="ts">
import { computed } from 'vue'
import { useNFTs } from '../composables'
import NFTCard from './NFTCard.vue'

const props = withDefaults(defineProps<{
  owner: string
  collection?: string
  columns?: number
}>(), {
  columns: 3,
})

const { nfts, loading, error } = useNFTs(props.owner)

const filtered = computed(() => {
  if (!props.collection) return nfts.value
  return nfts.value.filter(nft => nft.collection === props.collection)
})
</script>

<template>
  <div v-if="loading">Loading gallery...</div>
  <div v-else-if="error">Error: {{ error.message }}</div>
  <div v-else-if="filtered.length === 0">No NFTs found{{ collection ? ' in this collection' : '' }}</div>
  <div v-else :style="{ display: 'grid', gridTemplateColumns: `repeat(${columns}, 1fr)`, gap: '16px' }">
    <NFTCard v-for="nft in filtered" :key="nft.mint" :mint="nft.mint" :nft="nft" />
  </div>
</template>
