// packages/react/src/components/ProposalList.tsx
import React from 'react'
import type { CommonProps } from '../types'
import { useProposals } from '../hooks/useProposals'

export interface ProposalListProps extends CommonProps {
  daoAddress: string
  limit?: number
}

export function ProposalList({ daoAddress, limit = 10, className, style }: ProposalListProps): JSX.Element {
  const { proposals, loading, error } = useProposals(daoAddress)

  if (loading) return <div className={className} style={style} aria-busy={true}>Loading proposals...</div>
  if (error) return <div className={className} style={style} role="alert">Error loading proposals</div>
  if (proposals.length === 0) return <div className={className} style={style}>No proposals found</div>

  return (
    <ul className={className} style={{ listStyle: 'none', padding: 0, ...style }} role="list" aria-label="Proposals">
      {proposals.slice(0, limit).map((p) => (
        <li key={p.address} style={{ padding: '12px', borderBottom: '1px solid #eee' }}>
          <strong>{p.title}</strong>
          <span style={{ marginLeft: '8px', color: '#666' }}>{p.status}</span>
        </li>
      ))}
    </ul>
  )
}

// packages/vue/src/components/ProposalList.vue
<script setup lang="ts">
import { useProposals } from '../composables/useProposals'

const props = withDefaults(defineProps<{
  daoAddress: string
  limit?: number
}>(), { limit: 10 })

const { proposals, loading, error } = useProposals(props.daoAddress)
</script>

<template>
  <div v-if="loading" aria-busy="true">Loading proposals...</div>
  <div v-else-if="error" role="alert">Error loading proposals</div>
  <div v-else-if="proposals.length === 0">No proposals found</div>
  <ul v-else style="list-style: none; padding: 0;" role="list" aria-label="Proposals">
    <li v-for="p in proposals.slice(0, limit)" :key="p.address" style="padding: 12px; border-bottom: 1px solid #eee;">
      <strong>{{ p.title }}</strong>
      <span style="margin-left: 8px; color: #666;">{{ p.status }}</span>
    </li>
  </ul>
</template>
