// packages/react/src/components/ProposalDetails.tsx
import React from 'react'
import type { CommonProps } from '../types'

export interface ProposalDetailsProps extends CommonProps {
  address: string
  title: string
  description: string
  status: string
  proposer: string
  forVotes: bigint
  againstVotes: bigint
  abstainVotes: bigint
  startTime: bigint
  endTime: bigint
}

export function ProposalDetails({ address, title, description, status, proposer, forVotes, againstVotes, abstainVotes, startTime, endTime, className, style }: ProposalDetailsProps): JSX.Element {
  const totalVotes = forVotes + againstVotes + abstainVotes

  return (
    <div className={className} style={{ padding: '16px', ...style }} role="article" aria-label={`Proposal details: ${title}`}>
      <h2 style={{ margin: '0 0 4px' }}>{title}</h2>
      <span style={{ padding: '2px 8px', borderRadius: '4px', background: '#f0f0f0', fontSize: '12px' }}>{status}</span>
      <p style={{ color: '#666', fontSize: '12px', marginTop: '8px' }}>Proposed by: {proposer.slice(0, 8)}...</p>
      <p style={{ marginTop: '12px' }}>{description}</p>
      <div style={{ marginTop: '16px' }}>
        <h4 style={{ margin: '0 0 8px' }}>Votes</h4>
        <div style={{ fontSize: '14px' }}>
          <div>For: {forVotes.toString()}</div>
          <div>Against: {againstVotes.toString()}</div>
          <div>Abstain: {abstainVotes.toString()}</div>
          <div style={{ marginTop: '4px', fontWeight: 'bold' }}>Total: {totalVotes.toString()}</div>
        </div>
      </div>
    </div>
  )
}

// packages/vue/src/components/ProposalDetails.vue
<script setup lang="ts">
const props = defineProps<{
  address: string
  title: string
  description: string
  status: string
  proposer: string
  forVotes: bigint
  againstVotes: bigint
  abstainVotes: bigint
  startTime: bigint
  endTime: bigint
}>()

const totalVotes = props.forVotes + props.againstVotes + props.abstainVotes
</script>

<template>
  <div style="padding: 16px;" role="article" :aria-label="`Proposal details: ${title}`">
    <h2 style="margin: 0 0 4px;">{{ title }}</h2>
    <span style="padding: 2px 8px; border-radius: 4px; background: #f0f0f0; font-size: 12px;">{{ status }}</span>
    <p style="color: #666; font-size: 12px; margin-top: 8px;">Proposed by: {{ proposer.slice(0, 8) }}...</p>
    <p style="margin-top: 12px;">{{ description }}</p>
    <div style="margin-top: 16px;">
      <h4 style="margin: 0 0 8px;">Votes</h4>
      <div style="font-size: 14px;">
        <div>For: {{ forVotes.toString() }}</div>
        <div>Against: {{ againstVotes.toString() }}</div>
        <div>Abstain: {{ abstainVotes.toString() }}</div>
        <div style="margin-top: 4px; font-weight: bold;">Total: {{ totalVotes.toString() }}</div>
      </div>
    </div>
  </div>
</template>
