// packages/react/src/components/SolAmount.tsx
import React from 'react'
import type { CommonProps } from '../types'

export interface SolAmountProps extends CommonProps {
  amount: number | bigint
  decimals?: number
  showSymbol?: boolean
}

export function SolAmount({ amount, decimals = 4, showSymbol = true, className, style }: SolAmountProps): JSX.Element {
  const value = typeof amount === 'bigint' ? Number(amount) / 1e9 : amount

  return (
    <span className={className} style={style}>
      {value.toFixed(decimals)} {showSymbol && 'SOL'}
    </span>
  )
}

// packages/vue/src/components/SolAmount.vue
<script setup lang="ts">
import { computed } from 'vue'

const props = withDefaults(defineProps<{
  amount: number | bigint
  decimals?: number
  showSymbol?: boolean
}>(), {
  decimals: 4,
  showSymbol: true,
})

const value = computed(() => {
  const num = typeof props.amount === 'bigint' ? Number(props.amount) / 1e9 : props.amount
  return num.toFixed(props.decimals)
})
</script>

<template>
  <span>{{ value }} <template v-if="showSymbol">SOL</template></span>
</template>
